#docker-compose.yml
#run with: docker-compose up --build --scale service=2
version: '3'
services:
  traefik:
    image: "traefik"
    ports:
      - "8080:80"
    volumes:
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/traefik/dynamic_load.toml:/etc/traefik/dynamic_load.toml
  apiproxy:
    build: ./apiproxy
    ports:
      - "8081:8080"
  storage:
    build: ./storage
    ports:
      - "8082:8080"
  frontend:
    build: ./frontend
    ports:
      - "8083:8080"
  auth:
     build: ./auth
     ports:
      - "8084:8080"
  service:
    build: ./service
    ports:
      - "8085-8086:8080"
