#docker-compose.yml
version: '3'
services:
  service:
    build: .
    ports:
      - "8080:8081"
  traefik:
    image: "traefik"
    ports:
      - "8888:80"
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/dynamic_load.toml:/etc/traefik/dynamic_load.toml
