[http.routers.dashboard]
rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
entrypoints = ["web"]
service = "api@internal"

[http.routers.frontend]
rule = "PathPrefix(`/`)"
entrypoints = ["web"]
service = "frontend"
[http.services.frontend.loadBalancer.healthCheck]
path = "/health"
interval = "3s"
timeout = "1s"
[[http.services.coinservice.loadBalancer.servers]]
url = "http://127.0.0.1:8083"

[http.routers.apiproxy]
rule = "PathPrefix(`/api`)"
entrypoints = ["web"]
service = "apiproxy"
[http.services.apiproxy.loadBalancer.healthCheck]
path = "/health"
interval = "3s"
timeout = "1s"
[[http.services.apiproxy.loadBalancer.servers]]
url = "http://127.0.0.1:8081"

[http.routers.storage]
rule = "PathPrefix(`/storage`)"
entrypoints = ["web"]
service = "storage"
[http.services.storage.loadBalancer.healthCheck]
path = "/health"
interval = "3s"
timeout = "1s"
[[http.services.storage.loadBalancer.servers]]
url = "http://127.0.0.1:8082"

[http.routers.service]
rule = "PathPrefix(`/coinservice`)"
entrypoints = ["web"]
service = "coinservice"
[http.services.coinservice.loadBalancer.healthCheck]
path = "/health"
interval = "3s"
timeout = "1s"
[[http.services.coinservice.loadBalancer.servers]]
url = "http://172.17.0.1:8084"
[[http.services.coinservice.loadBalancer.servers]]
url = "http://172.17.0.1:8085"
