[http.routers.dashboard]
rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
entrypoints = ["web"]
service = "api@internal"

[http.middlewares]
[http.middlewares.proxy-stripprefix.stripPrefix]
prefixes = ["/proxy"]
[http.middlewares.storage-stripprefix.stripPrefix]
prefixes = ["/storage"]
[http.middlewares.coinservice-stripprefix.stripPrefix]
prefixes = ["/coinservice"]

[http.routers.apiproxy]
rule = "PathPrefix(`/proxy`)"
middlewares = ["proxy-stripprefix"]
entrypoints = ["web"]
service = "apiproxy"
[[http.services.apiproxy.loadBalancer.servers]]
url = "http://172.17.0.1:8081"

[http.routers.storage]
rule = "PathPrefix(`/storage`)"
middlewares = ["storage-stripprefix"]
entrypoints = ["web"]
service = "storage"
[[http.services.storage.loadBalancer.servers]]
url = "http://172.17.0.1:8082"

[http.routers.frontend]
rule = "PathPrefix(`/`)"
entrypoints = ["web"]
service = "frontend"
[[http.services.frontend.loadBalancer.servers]]
url = "http://172.17.0.1:8083"

[http.routers.auth]
rule = "PathPrefix(`/auth`)"
entrypoints = ["web"]
service = "auth"
[[http.services.auth.loadBalancer.servers]]
url = "http://172.17.0.1:8084"

[http.routers.service]
rule = "PathPrefix(`/coinservice`)"
middlewares = ["coinservice-stripprefix"]
entrypoints = ["web"]
service = "coinservice"
[[http.services.coinservice.loadBalancer.servers]]
url = "http://172.17.0.1:8085"
[[http.services.coinservice.loadBalancer.servers]]
url = "http://172.17.0.1:8086"
