[entryPoints.web]
address = ":80"

[api]
dashboard = true

[providers.file]
filename = "/etc/traefik/dynamic_load.toml"

[log]
filePath = "traefik.log"
level = "INFO"

[accessLog]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "127.0.0.1"
watch = true
exposedbydefault = false
network = "proxy"